services:
  my-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: my-db
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: db
    depends_on:
      - my-db